name: Python linters

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install APT dependencies
      run: |
        sudo apt-get install libsdl2-dev
    - name: Install Pip packages
      run: |
        python -m pip install -U pip
        pip install flake8 mypy isort black --requirement requirements.txt
    - name: Flake8
      if: always()
      uses: liskin/gh-problem-matcher-wrap@v1
      with:
        linters: flake8
        run: flake8 .
    - name: MyPy
      if: always()
      uses: liskin/gh-problem-matcher-wrap@v1
      with:
        linters: mypy
        run: mypy --show-column-numbers .
    - name: isort
      if: always()
      uses: liskin/gh-problem-matcher-wrap@v1
      with:
        linters: isort
        run: isort --check .
    - name: Black
      run: |
        black --check .
